Api::CustomAudiences
maiha/twitter-ads.cr pull request #4
Opened 2022-06-30 09:02 UTC by norihito-sato-ss

2022-06-30 14:15 UTC, maiha requested changes

2022-06-30 14:15 UTC, maiha commented on spec/twitter-ads/api/custom_audiences_spec.cr
> +      client.line_items("18ce54d4x5t", with_deleted: true, with_draft: true)
* `line_items` → `custom_audiences`
* `with_draft` はAPIに存在しないので削除で

2022-06-30 14:15 UTC, maiha commented on src/twitter-ads/api/custom-audiences.cr
> +  def custom_audiences(account_id : String, with_deleted : Bool = false, with_draft : Bool = false, count : Int32 = 200, cursor : String = "") : Api::CustomAudiences
ditto `with_draft`

2022-07-01 00:32 UTC, maiha requested changes
モデル(データを入れる器)系は、1データが入るので、名前を単数形にして下さい。

#### 単数形
* proto, model

#### 複数形
* API, json, samples

2022-07-01 00:35 UTC, maiha requested changes

2022-07-01 00:35 UTC, maiha commented on proto/custom-audiences.proto
> +syntax = "proto2";
ファイル名はハイフンでなくアンダーバーにして下さい

2022-07-01 00:35 UTC, maiha commented on src/twitter-ads/api/custom-audiences.cr
> +  def custom_audiences(account_id : String, with_deleted : Bool = false, with_draft : Bool = false, count : Int32 = 200, cursor : String = "") : Api::CustomAudiences
ditto ファイル名

2022-07-01 00:35 UTC, maiha commented on src/twitter-ads/models/custom-audiences.cr
> +class TwitterAds::CustomAudiences
ditto: ファイル名

2022-07-01 00:35 UTC, maiha commented on src/twitter-ads/proto/custom-audiences.pb.cr
> +## Generated from custom-audiences.proto
ditto: ファイル名

2022-07-01 03:53 UTC, norihito-sato-ss commented on spec/twitter-ads/api/custom_audiences_spec.cr
> +      client.line_items("18ce54d4x5t", with_deleted: true, with_draft: true)
ありがとうございます。承知しました。:bow:

2022-07-01 03:59 UTC, norihito-sato-ss commented on src/twitter-ads/api/custom-audiences.cr
> +  def custom_audiences(account_id : String, with_deleted : Bool = false, with_draft : Bool = false, count : Int32 = 200, cursor : String = "") : Api::CustomAudiences
ありがとうございます。承知しました。🙇

2022-07-01 04:06 UTC, norihito-sato-ss commented on proto/custom-audiences.proto
> +syntax = "proto2";
承知しました。🙇

2022-07-01 04:06 UTC, norihito-sato-ss commented on src/twitter-ads/models/custom-audiences.cr
> +class TwitterAds::CustomAudiences
🙇

2022-07-01 04:06 UTC, norihito-sato-ss commented on src/twitter-ads/proto/custom-audiences.pb.cr
> +## Generated from custom-audiences.proto
承知しました。🙇

2022-07-01 19:31 UTC, maiha requested changes

2022-07-01 19:31 UTC, maiha commented on src/twitter-ads/models/custom_audience.cr
> +class TwitterAds::CustomAudiences
modelの名前は単数形でお願いします 🙇

2022-07-01 19:31 UTC, maiha commented on src/twitter-ads/models/custom_audience.cr
> +    TwitterAds::Proto::CustomAudiences.new(
ditto: 単数形

2022-07-04 02:30 UTC, norihito-sato-ss commented on src/twitter-ads/models/custom_audience.cr
> +class TwitterAds::CustomAudiences
ありがとうございます。🙇
承知しました。

2022-07-04 02:30 UTC, norihito-sato-ss commented on src/twitter-ads/models/custom_audience.cr
> +    TwitterAds::Proto::CustomAudiences.new(
ありがとうございます。🙇
承知しました。

2022-07-04 14:23 UTC, maiha approved these changes
👍

2022-07-04 14:25 UTC, merged