[wip] add tweets_lookup
maiha/twitter-ads.cr pull request #6
Opened 2022-08-31 09:58 UTC by norihito-sato-ss

2022-08-31 14:50 UTC, maiha requested changes
追加)
1. `spec/twitter-ads/api/tweets_lookup_spec.cr` (status_lookup_spec.crを参考にする)
2. `spec/mock/2/tweets.json` (↑で必要。1.1/status_lookup.jsonぽいものを作る)

2022-08-31 14:50 UTC, maiha commented on src/twitter-ads/api/tweets_lookup.cr
> +  def tweets_lookup(id : String | Array(String)) : Api::TweetsLookup
引数で、APIにある全てのQuery Parameterを受け取れるようにして下さい。
* https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets
* 省略可能なparameterは `String = ""`

```crystal
  def tweets_lookup(id : String | Array(String), expansions : String = "", ..., user_fields : String = "")
```

2022-08-31 14:50 UTC, maiha commented on src/twitter-ads/api/tweets_lookup.cr
> +      "tweet.fields" => "reply_settings,author_id,lang,source,created_at,conversation_id",
↑のメソッド引数に対応して下さい。

2022-08-31 14:50 UTC, maiha commented on json/twitter_ads/tweets_lookup.json
> +    }
APIに追加した全パラメータ(expansions等)を指定した時の全項目を記載して下さい。
* 全項目はAPIを実行して調べる
* 値は適当に変更する
* String, Intなど、protoに入りそうな型だけでよい
* objectやdataからはみ出してる項目も無視してよい

2022-08-31 14:50 UTC, maiha commented on proto/tweets_lookup.proto
> +message TweetsLookup {
↑のJSONから再生成

2022-08-31 14:50 UTC, maiha commented on samples/api/tweets_lookup.cr
> +client.tweets_lookup(tweet_ids).each do |c|
reply_settingsを追加 (オプション引数の動作確認)

2022-08-31 14:50 UTC, maiha commented on src/twitter-ads/models/tweets_lookup.cr
> +class TwitterAds::TweetsLookup
再生成

2022-08-31 14:50 UTC, maiha commented on src/twitter-ads/proto/tweets_lookup.pb.cr
> +## Generated from tweets_lookup.proto
再生成

2022-08-31 14:50 UTC, maiha commented on src/twitter-ads/api/tweets_lookup.cr
> +    resource_none
```suggestion
    resource_collection TweetsLookup
```

これで JSON の `.data` 以下を `TweetsLookup` モデルの配列とみなして parse することになります。

2022-08-31 14:50 UTC, maiha commented on samples/api/tweets_lookup.cr
> +  puts "+ TweetsLookup(%s) # %s" % [c.id_str.inspect, c.text.inspect]
`c.id_str` → `c.id`

2022-09-01 05:39 UTC, norihito-sato-ss commented on src/twitter-ads/api/tweets_lookup.cr
> +  def tweets_lookup(id : String | Array(String)) : Api::TweetsLookup
承知しました。

2022-09-01 05:39 UTC, norihito-sato-ss commented on src/twitter-ads/api/tweets_lookup.cr
> +      "tweet.fields" => "reply_settings,author_id,lang,source,created_at,conversation_id",
承知しました。

2022-09-01 06:17 UTC, norihito-sato-ss commented on samples/api/tweets_lookup.cr
> +  puts "+ TweetsLookup(%s) # %s" % [c.id_str.inspect, c.text.inspect]
ありがとうございます。:pray:
修正します。

2022-09-01 08:24 UTC, norihito-sato-ss commented on json/twitter_ads/tweets_lookup.json
> +    }
承知しました。
expansions を指定してもレスポンスがない項目があったので、もう少し調査してみます。

2022-09-01 08:25 UTC, norihito-sato-ss commented on proto/tweets_lookup.proto
> +message TweetsLookup {
承知しました。

2022-09-01 08:36 UTC, norihito-sato-ss commented on src/twitter-ads/api/tweets_lookup.cr
> +    resource_none
ありがとうございます。修正します。

2022-09-01 08:37 UTC, norihito-sato-ss commented on src/twitter-ads/proto/tweets_lookup.pb.cr
> +## Generated from tweets_lookup.proto
承知しました。

2022-09-01 08:37 UTC, norihito-sato-ss commented on src/twitter-ads/models/tweets_lookup.cr
> +class TwitterAds::TweetsLookup
承知しました。

2022-09-02 05:09 UTC, norihito-sato-ss commented on samples/api/tweets_lookup.cr
> +client.tweets_lookup(tweet_ids).each do |c|
承知しました。

2022-09-02 05:54 UTC, norihito-sato-ss commented on json/twitter_ads/tweets_lookup.json
> +    }
以下を参考にレスポンスデータを作成しました。
https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet

2022-09-02 06:22 UTC, maiha requested changes
LGTM 👍 
細かい所を2件だけ、Commit suggestionお願いします 🙇

2022-09-02 06:22 UTC, maiha commented on samples/api/tweets_lookup.cr
> +client.tweets_lookup(id: tweet_ids, tweet_fields: tweet_fields).each do |c|
短い仮引数は、そのオブジェクトの型にしたいです。
ここでは `TweetsLookup` 型が入るので `t` で 🙏 

```suggestion
client.tweets_lookup(id: tweet_ids, tweet_fields: tweet_fields).each do |t|
```

`Commit suggestion` でOKです

2022-09-02 06:22 UTC, maiha commented on samples/api/tweets_lookup.cr
> +  puts "+ TweetsLookup(%s) # %s" % [c.id.inspect, c.text.inspect]
せっかく reply_settings を取得したのでそれも表示で。
```suggestion
  puts "+ TweetsLookup(%s) # (%s)%s" % [t.id.inspect, t.reply_settings, t.text.inspect]
```

Commit suggestion でOKです

2022-09-02 06:22 UTC, maiha commented on spec/twitter-ads/api/tweets_lookup_spec.cr
> +      tweets_lookup.reply_settings.should eq "everyone"
reply_settings チェックしてるの良き 👍

2022-09-02 06:33 UTC, maiha approved these changes
👍

2022-09-02 06:33 UTC, merged

2022-09-06 02:51 UTC, norihito-sato-ss commented on spec/twitter-ads/api/tweets_lookup_spec.cr
> +      tweets_lookup.reply_settings.should eq "everyone"
ご確認ありがとうございます🙇